### ISSUE TITLE
내 위치를 클릭하면 바다 한가운데로 이동합니다.

### ISSUE THREAD

**Issue by seongjin605** [stories2/corona19kr#2]
![image](https://user-images.githubusercontent.com/16683075/76914713-7b6dd980-68fe-11ea-9136-a6a79995c86f.png)

### OS
5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

**Comment by stories2** [comment]
![aaaaaa](https://user-images.githubusercontent.com/16532326/76918237-3307e900-6909-11ea-90b7-646da79b05aa.png)

예상되는 원인은 자신의 위치를 가져오지 못 하였거나 위치 허용을 하지 않은 경우 위도 경도를 0,0 에 맞춰놓은 상태로 끝내기 때문으로 파악됨

192e6ec 에서는 위치 가져오기가 실패할 경우 기본 위도, 경도로 강제 이동하게끔 수정함
